/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cn.zoneco.openplatform.model.impl;

import cn.zoneco.openplatform.model.AttachmentInfo;
import cn.zoneco.openplatform.service.AttachmentInfoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the AttachmentInfo service. Represents a row in the &quot;t_attachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AttachmentInfoImpl}.
 * </p>
 *
 * @author fxbird
 * @see AttachmentInfoImpl
 * @see cn.zoneco.openplatform.model.AttachmentInfo
 * @generated
 */
public abstract class AttachmentInfoBaseImpl extends AttachmentInfoModelImpl
	implements AttachmentInfo {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a attachment info model instance should use the {@link AttachmentInfo} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			AttachmentInfoLocalServiceUtil.addAttachmentInfo(this);
		}
		else {
			AttachmentInfoLocalServiceUtil.updateAttachmentInfo(this);
		}
	}
}