/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cn.zoneco.openplatform.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CallLog service. Represents a row in the &quot;t_log&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link cn.zoneco.openplatform.model.impl.CallLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cn.zoneco.openplatform.model.impl.CallLogImpl}.
 * </p>
 *
 * @author fxbird
 * @see CallLog
 * @see cn.zoneco.openplatform.model.impl.CallLogImpl
 * @see cn.zoneco.openplatform.model.impl.CallLogModelImpl
 * @generated
 */
public interface CallLogModel extends BaseModel<CallLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a call log model instance should use the {@link CallLog} interface instead.
	 */

	/**
	 * Returns the primary key of this call log.
	 *
	 * @return the primary key of this call log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this call log.
	 *
	 * @param primaryKey the primary key of this call log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the log ID of this call log.
	 *
	 * @return the log ID of this call log
	 */
	public long getLogId();

	/**
	 * Sets the log ID of this call log.
	 *
	 * @param logId the log ID of this call log
	 */
	public void setLogId(long logId);

	/**
	 * Returns the user name of this call log.
	 *
	 * @return the user name of this call log
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this call log.
	 *
	 * @param userName the user name of this call log
	 */
	public void setUserName(String userName);

	/**
	 * Returns the resource name of this call log.
	 *
	 * @return the resource name of this call log
	 */
	@AutoEscape
	public String getResourceName();

	/**
	 * Sets the resource name of this call log.
	 *
	 * @param resourceName the resource name of this call log
	 */
	public void setResourceName(String resourceName);

	/**
	 * Returns the start time of this call log.
	 *
	 * @return the start time of this call log
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this call log.
	 *
	 * @param startTime the start time of this call log
	 */
	public void setStartTime(Date startTime);

	/**
	 * Returns the end time of this call log.
	 *
	 * @return the end time of this call log
	 */
	public Date getEndTime();

	/**
	 * Sets the end time of this call log.
	 *
	 * @param endTime the end time of this call log
	 */
	public void setEndTime(Date endTime);

	/**
	 * Returns the log status of this call log.
	 *
	 * @return the log status of this call log
	 */
	@AutoEscape
	public String getLogStatus();

	/**
	 * Sets the log status of this call log.
	 *
	 * @param logStatus the log status of this call log
	 */
	public void setLogStatus(String logStatus);

	/**
	 * Returns the log message of this call log.
	 *
	 * @return the log message of this call log
	 */
	@AutoEscape
	public String getLogMessage();

	/**
	 * Sets the log message of this call log.
	 *
	 * @param logMessage the log message of this call log
	 */
	public void setLogMessage(String logMessage);

	/**
	 * Returns the user ID of this call log.
	 *
	 * @return the user ID of this call log
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this call log.
	 *
	 * @param userId the user ID of this call log
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this call log.
	 *
	 * @return the user uuid of this call log
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this call log.
	 *
	 * @param userUuid the user uuid of this call log
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the resource ID of this call log.
	 *
	 * @return the resource ID of this call log
	 */
	public long getResourceId();

	/**
	 * Sets the resource ID of this call log.
	 *
	 * @param resourceId the resource ID of this call log
	 */
	public void setResourceId(long resourceId);

	/**
	 * Returns the in msg of this call log.
	 *
	 * @return the in msg of this call log
	 */
	@AutoEscape
	public String getInMsg();

	/**
	 * Sets the in msg of this call log.
	 *
	 * @param inMsg the in msg of this call log
	 */
	public void setInMsg(String inMsg);

	/**
	 * Returns the out msg of this call log.
	 *
	 * @return the out msg of this call log
	 */
	@AutoEscape
	public String getOutMsg();

	/**
	 * Sets the out msg of this call log.
	 *
	 * @param outMsg the out msg of this call log
	 */
	public void setOutMsg(String outMsg);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CallLog callLog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CallLog> toCacheModel();

	@Override
	public CallLog toEscapedModel();

	@Override
	public CallLog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}